---
ID: "8bf25f6a-9784-4f8d-a3ef-6af6a2382a04"
Parent: "f15b3095-ff78-444b-97ee-5ae9ae7bbb59"
Template: "6d82fcd8-c379-443c-97a9-c6423c71e7d5"
Path: /sitecore/system/Modules/PowerShell/Script Library/SPE/Samples/Training Modules
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/jar_coffee_bean.png
- ID: "218ca464-cb77-4c97-b141-34871ecae00b"
  Hint: Enabled
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Fields:
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: Provides a way to enable or disable the Training modules.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190723T030916Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c730d1ea-30f8-4812-bb55-68df95938d57"
