---
ID: "9197dae0-2896-4f5a-b122-3ad96372e4d5"
Parent: "19c4fc86-35f6-42f5-ba3d-5575dce7013a"
Template: "ab154d3d-1126-4ab4-ac21-8b86e6bd70ea"
Path: /sitecore/system/Modules/PowerShell/Script Library/SPE/Maintenance/System Maintenance/Control Panel/Database
DB: master
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: ** Database **
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190718T201759Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "76ea5203-29d0-4f7b-ab72-27da5cd7d52a"
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Database
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20130713T155336
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8e5d6460-3ac8-4bb6-b915-95f412ec4bf1"
