---
ID: "25c829e2-02b8-4132-8065-4f8606960ab4"
Parent: "bb48d97a-3b30-4ec2-9f2b-88ce27970983"
Template: "1ab4f9ad-b004-413c-8924-3e07143a614b"
Path: /sitecore/content/Applications/PowerShell/PowerShellIse/Meta/EditConsoleSettings
DB: core
SharedFields:
- ID: "4431914a-c40b-437c-8add-d2ed12cc8cc3"
  Hint: Icon
  Value: people/16x16/cubes_blue.png
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
- ID: "cf738220-908d-4c3f-9482-32e625daf13c"
  Hint: Fields
  Value: FontSize|FontFamily|HostWidth|ForegroundColor|BackgroundColor
Languages:
- Language: da
  Fields:
  - ID: "108d3a63-baaa-4560-86d8-3a112ed84717"
    Hint: Header
    Value: Opsætning af script runtime
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190718T151820Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "649865c8-846f-488f-b259-c72014b3fab5"
- Language: en
  Fields:
  - ID: "108d3a63-baaa-4560-86d8-3a112ed84717"
    Hint: Header
    Value: Script runtime settings
  - ID: "5f0812af-d370-4292-afee-f26a39b7406d"
    Hint: Tooltip
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20090528T094300
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9041a91d-200f-4885-9a17-82c817891acf"
- Language: "ja-JP"
  Fields:
  - ID: "108d3a63-baaa-4560-86d8-3a112ed84717"
    Hint: Header
    Value: スクリプトランタイムの設定
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160823T075958
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ab7f1da4-94e5-4f4a-8c08-f79d0e964531"
