services:
  cm:
    environment:
      Sitecore_AppSettings_role:define: Standalone
      SITECORE_DEVELOPMENT_PATCHES: CustomErrorsOff
    volumes:
      - ..\deploy:C:\deploy
      - ..\unicorn:C:\inetpub\wwwroot\App_Data\Unicorn
      - ..\releases:C:\inetpub\wwwroot\App_Data\packages
      - ..\modules:C:\modules:ro
      - .\tools:C:\tools:ro
    entrypoint: powershell -Command "& C:\tools\entrypoints\iis\Development.ps1"