---
ID: "129ab3db-3b3a-41b7-9cfb-6b7587650c2e"
Parent: "190512e7-f6cf-41b0-a2e6-1286a3247ac4"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: /sitecore/system/Modules/PowerShell/Script Library/SPE/Training/Web API and Remoting/Simple Web API/Web API/TrainingWebApi
DB: master
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    <#
        .EXAMPLE
            The following returns the home item and hits children. This assumes you have published the this item to the web database.
            Use user and password arguments to interact with the master database.
            
            $username = "admin"
            $password = "b"
            
            $pair = "$($username):$($password)"
            
            $encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($pair))
            
            $basicAuthValue = "Basic $encodedCreds"
            
            $headers = @{
                Authorization = $basicAuthValue
            }
            
            Invoke-RestMethod -Headers $headers -Uri "https://spe.dev.local/-/script/v2/master/TrainingWebApi?offset=3&limit=2&fields=(Name,ItemPath,Id)"
    #>
    
    Import-Function -Name Invoke-ApiScript
    
    Invoke-ApiScript -ScriptBlock {
        @(Get-Item -Path master:\content\home) + @(Get-ChildItem -Path master:\content\home -Recurse)
    } -Arguments $scriptArguments
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190614T030011Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a62ecfba-8f53-493b-a928-de120c26ae5e"
