---
ID: "e7ab8e76-96f0-4a8d-b80b-d9971515d1e4"
Parent: "e96411fe-97f1-47ac-80e3-9315593e7feb"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: /sitecore/system/Modules/PowerShell/Script Library/SPE/Maintenance/System Maintenance/Tasks/Clean up link databases
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/data.png
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    <#
        .SYNOPSIS
            Runs a clean up for each link database.
            
        .NOTES
            Michael West
    #>
    
    foreach($database in Get-Database) {
        if(!$database.ReadOnly) {
            Write-Log "Rebuilding the $($database) link database."
            $time = Measure-Command {
                [Sitecore.Globals]::LinkDatabase.Rebuild($database)
            }
            Write-Log "Completed rebuilding the $($database) link database in $($time.TotalSeconds) seconds."
        }
    }
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Rens link databasen
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190718T201821Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "233e0603-fed9-4b4c-a695-7cddba950d65"
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Clean up link databases
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150516T222058
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "11b6d65f-399b-4f7b-abfd-1d3c7d1169a5"
