---
ID: "f993eb2a-6ba8-4d36-bc05-e7340fdf1b28"
Parent: "e96411fe-97f1-47ac-80e3-9315593e7feb"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: /sitecore/system/Modules/PowerShell/Script Library/SPE/Maintenance/System Maintenance/Tasks/Rebuild content search indexes
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/rebuild_all_indexes.png
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    <#
        .SYNOPSIS
            Rebuilds all the content search indexes.
            
        .NOTES
            Michael West, Adam Najmanowicz
    #>
    
    foreach($index in Get-SearchIndex) {
        Write-Log "Rebuilding the $($index.Name) search index."
        $time = Measure-Command {
            Initialize-SearchIndex -Index $index
        }
        Write-Log "Completed rebuilding the $($index.Name) search index in $($time.TotalSeconds) seconds."
    }
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Genbyg indholdssøgeindeks
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190718T201821Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "af798f17-5df0-44a0-b66a-81bd42717135"
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Rebuild content search indexes
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150515T014932
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3480bca9-2525-46e9-8a74-9bfff8aff72a"
