---
ID: "c6047ca6-0a24-4966-a9d8-e12bfcaa6ff6"
Parent: "58b6a738-b732-4855-b4ec-302b7bf61cb1"
Template: "1db34c92-03b0-4475-9a39-da14e4d9d8fc"
Path: /sitecore/content/Applications/PowerShell/PowerShellIse/Ribbon/Settings/Preferences/Settings
DB: core
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/window_gear.png
- ID: "1193b1a3-0148-413f-a979-49b39aa4a2af"
  Hint: ID
  Value: iseSettingsDropdown
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
- ID: "d47ed548-84d5-4622-9886-5cc164727507"
  Hint: Icon
  Value: Office/32x32/window_gear.png
- ID: "dbbf9ee3-c30e-4456-a81f-ed8c2e8df91b"
  Hint: Click
  Value: "ise:editsettingsdropdown(id=$Target)"
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190718T151826Z
    - ID: "4df6da21-e745-444c-956e-1d4a96ab8821"
      Hint: Header
      Value: Opsætning
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "39c3efb6-a46e-4209-a6ee-cac95ea8a8e0"
    - ID: "a1a31a93-c4a0-4396-b629-67c33001a3cf"
      Hint: Tooltip
      Value: Editer din personlige opsætning.
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20060721T095816
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "4df6da21-e745-444c-956e-1d4a96ab8821"
      Hint: Header
      Value: Settings
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea1944ab-b43e-4f29-907b-56061d39bef0"
    - ID: "a1a31a93-c4a0-4396-b629-67c33001a3cf"
      Hint: Tooltip
      Value: Edit your personal settings.
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20060320T102016
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160823T075959
    - ID: "4df6da21-e745-444c-956e-1d4a96ab8821"
      Hint: Header
      Value: 設定
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb7ea281-6d08-4aa0-85ee-409a094872f1"
    - ID: "a1a31a93-c4a0-4396-b629-67c33001a3cf"
      Hint: Tooltip
      Value: 個人の設定の編集
