---
ID: "08b4ba05-759b-456a-8ca1-a00a8db99fad"
Parent: "36657c88-3f10-4b16-a3c7-03e011b0f6c2"
Template: "b6a55ac6-a602-4c09-ac3a-1d2938621d5b"
Path: /sitecore/system/Modules/PowerShell/Script Library/SPE/Training
DB: master
Languages:
- Language: en
  Fields:
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: "Check out working examples to help you along with your exploration of SPE!"
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190614T021423Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "104aa152-bd0d-4869-b062-bb82dead4fbd"
