---
ID: "86fbee0d-6190-40ba-b045-511969b65745"
Parent: "b9a75c9f-b578-4833-99fb-c4158bc8768b"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: /sitecore/system/Modules/PowerShell/Script Library/SPE/Maintenance/Media Library Maintenance/Tasks/Delete unused media items older than 30 days
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/garbage_half_full.png
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    <#
        .SYNOPSIS
            Moves items to the recycle bin which are more than 30 days old and have no references.
        
        .NOTES
            Michael West
    #>
    
    filter Skip-MissingReference {
        $linkDb = [Sitecore.Globals]::LinkDatabase
        if($linkDb.GetReferrerCount($_) -eq 0) {
            $_
        }
    }
    
    $lastMonth = [datetime]::Today.AddDays(-30)
    
    $items = Get-ChildItem -Path "master:\sitecore\media library" -Recurse | 
        Where-Object { $_.TemplateID -ne [Sitecore.TemplateIDs]::MediaFolder } |
        Where-Object { $_.__Owner -ne "sitecore\admin" -and $_.__Updated -lt $lastMonth } |
        Skip-MissingReference
    
    if($items) {
        Write-Log "Removing $($items.Length) item(s) older than 30 days."
        $items | Remove-Item
    }
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Slet ubrugte medie elementer ældre end 30 dage
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190718T201759Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e4600b02-897f-4555-822e-cfdfec3f803b"
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Delete unused media items older than 30 days
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141017T232308
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2c61857c-0b04-48c8-b62e-60838c5a0a03"
