---
ID: "40d0a766-25d1-4b84-b20c-8be9f2e54d53"
Parent: "fdd5b2d5-31be-41c3-aa76-64e5cc63b187"
Template: "ec6d62a5-5d00-4329-8958-8ac1ad100ebb"
Path: /sitecore/content/Applications/PowerShell/PowerShellIse/Ribbon/Settings
DB: core
SharedFields:
- ID: "12c1ceb4-f549-472a-97ed-99bff70eb84e"
  Hint: ID
  Value: SettingsStrip
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: da
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190718T151820Z
    - ID: "5453dc07-6a17-48ba-8d05-17db90a2e795"
      Hint: Header
      Value: Opsætning
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b837602a-705a-4572-8cf5-4b2e1886e063"
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20060721T095446
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5453dc07-6a17-48ba-8d05-17db90a2e795"
      Hint: Header
      Value: Settings
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a7a49598-8947-4f08-bd8e-2daccee96baf"
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 20060320T101959
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160823T075959
    - ID: "5453dc07-6a17-48ba-8d05-17db90a2e795"
      Hint: Header
      Value: 設定
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e642a255-7bb0-42ff-9a19-dc5f4c1f6e43"
